CREATE TABLE ATT_CLASSES (
  ATT_CLASS_ID INTEGER,
  ATT_CLASS TEXT,
  PRIMARY KEY (ATT_CLASS_ID)
);

CREATE TABLE OBJ_CLASSES (
  OBJ_CLASS_ID INTEGER,
  OBJ_CLASS TEXT,
  PRIMARY KEY (OBJ_CLASS_ID)
);

CREATE TABLE IMG_OBJ (
  IMG_ID INTEGER,
  OBJ_SAMPLE_ID INTEGER,
  OBJ_CLASS_ID INTEGER,
  X INTEGER,
  Y INTEGER,
  W INTEGER,
  H INTEGER,
  FOREIGN KEY (OBJ_CLASS_ID) REFERENCES OBJ_CLASSES(OBJ_CLASS_ID)
);

CREATE TABLE IMG_OBJ_ATT (
  IMG_ID INTEGER,
  ATT_CLASS_ID INTEGER,
  OBJ_SAMPLE_ID INTEGER,
  FOREIGN KEY (IMG_ID) REFERENCES IMG_OBJ(IMG_ID),
  FOREIGN KEY (ATT_CLASS_ID) REFERENCES ATT_CLASSES(ATT_CLASS_ID),
  FOREIGN KEY (OBJ_SAMPLE_ID) REFERENCES IMG_OBJ(OBJ_SAMPLE_ID)
);

CREATE TABLE PRED_CLASSES (
  PRED_CLASS_ID INTEGER,
  PRED_CLASS TEXT,
  PRIMARY KEY (PRED_CLASS_ID)
);

CREATE TABLE IMG_REL (
  IMG_ID INTEGER,
  PRED_CLASS_ID INTEGER,
  OBJ1_SAMPLE_ID INTEGER,
  OBJ2_SAMPLE_ID INTEGER,
  FOREIGN KEY (IMG_ID) REFERENCES IMG_OBJ(IMG_ID),
  FOREIGN KEY (PRED_CLASS_ID) REFERENCES PRED_CLASSES(PRED_CLASS_ID),
  FOREIGN KEY (OBJ1_SAMPLE_ID) REFERENCES IMG_OBJ(OBJ_SAMPLE_ID),
  FOREIGN KEY (OBJ2_SAMPLE_ID) REFERENCES IMG_OBJ(OBJ_SAMPLE_ID)
);
