CREATE TABLE resultsdata15 (
  sample_pk REAL PRIMARY KEY,
  commod TEXT,
  commtype TEXT,
  lab TEXT,
  pestcode TEXT,
  testclass TEXT,
  concen REAL,
  lod REAL,
  conunit TEXT,
  confmethod TEXT,
  confmethod2 TEXT,
  annotate TEXT,
  quantitate TEXT,
  mean TEXT,
  extract TEXT,
  determin TEXT
);
CREATE TABLE sampledata15 (
  sample_pk REAL PRIMARY KEY,
  state TEXT,
  year TEXT,
  month TEXT,
  day TEXT,
  site TEXT,
  commod TEXT,
  source_id TEXT,
  variety TEXT,
  origin TEXT,
  country TEXT,
  disttype TEXT,
  commtype TEXT,
  claim TEXT,
  quantity REAL,
  growst TEXT,
  packst TEXT,
  distst TEXT,
  FOREIGN KEY (sample_pk) REFERENCES resultsdata15(sample_pk)
);
