CREATE TABLE awards_players (
  playerID TEXT,
  award TEXT,
  year INTEGER,
  lgID TEXT,
  note TEXT,
  pos TEXT,
  FOREIGN KEY (playerID) REFERENCES players(playerID)
);

CREATE TABLE coaches (
  coachID TEXT,
  year INTEGER,
  tmID TEXT,
  lgID TEXT,
  stint INTEGER,
  won INTEGER,
  lost INTEGER,
  post_wins INTEGER,
  post_losses INTEGER,
  FOREIGN KEY (year) REFERENCES teams(year),
  FOREIGN KEY (tmID) REFERENCES teams(tmID)
);

CREATE TABLE draft (
  id INTEGER,
  draftYear INTEGER,
  draftRound INTEGER,
  draftSelection INTEGER,
  draftOverall INTEGER,
  tmID TEXT,
  firstName TEXT,
  lastName TEXT,
  suffixName TEXT,
  playerID TEXT,
  draftFrom TEXT,
  lgID TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (draftYear) REFERENCES teams(year),
  FOREIGN KEY (tmID) REFERENCES teams(tmID)
);

CREATE TABLE player_allstar (
  playerID TEXT,
  last_name TEXT,
  first_name TEXT,
  season_id INTEGER,
  conference TEXT,
  league_id TEXT,
  games_played INTEGER,
  minutes INTEGER,
  points INTEGER,
  o_rebounds INTEGER,
  d_rebounds INTEGER,
  rebounds INTEGER,
  assists INTEGER,
  steals INTEGER,
  blocks INTEGER,
  turnovers INTEGER,
  personal_fouls INTEGER,
  fg_attempted INTEGER,
  fg_made INTEGER,
  ft_attempted INTEGER,
  ft_made INTEGER,
  three_attempted INTEGER,
  three_made INTEGER,
  FOREIGN KEY (playerID) REFERENCES players(playerID)
);

CREATE TABLE players (
  playerID TEXT,
  useFirst TEXT,
  firstName TEXT,
  middleName TEXT,
  lastName TEXT,
  nameGiven TEXT,
  fullGivenName TEXT,
  nameSuffix TEXT,
  nameNick TEXT,
  pos TEXT,
  firstseason INTEGER,
  lastseason INTEGER,
  height REAL,
  weight INTEGER,
  college TEXT,
  collegeOther TEXT,
  birthDate TEXT,
  birthCity TEXT,
  birthState TEXT,
  birthCountry TEXT,
  highSchool TEXT,
  hsCity TEXT,
  hsState TEXT,
  hsCountry TEXT,
  deathDate TEXT,
  race TEXT,
  PRIMARY KEY (playerID)
);

CREATE TABLE teams (
  year INTEGER,
  lgID TEXT,
  tmID TEXT,
  franchID TEXT,
  confID TEXT,
  divID TEXT,
  rank INTEGER,
  confRank INTEGER,
  playoff TEXT,
  name TEXT,
  o_fgm INTEGER,
  o_ftm INTEGER,
  o_pts INTEGER,
  d_pts INTEGER,
  homeWon INTEGER,
  homeLost INTEGER,
  awayWon INTEGER,
  awayLost INTEGER,
  won INTEGER,
  lost INTEGER,
  games INTEGER,
  arena TEXT
);

CREATE TABLE awards_coaches (
  id INTEGER,
  year INTEGER,
  coachID TEXT,
  award TEXT,
  lgID TEXT,
  note TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (year) REFERENCES coaches(year),
  FOREIGN KEY (coachID) REFERENCES coaches(coachID)
);

CREATE TABLE players_teams (
  id INTEGER,
  playerID TEXT,
  year INTEGER,
  stint INTEGER,
  tmID TEXT,
  lgID TEXT,
  GP INTEGER,
  GS INTEGER,
  minutes INTEGER,
  points INTEGER,
  oRebounds INTEGER,
  dRebounds INTEGER,
  rebounds INTEGER,
  assists INTEGER,
  steals INTEGER,
  blocks INTEGER,
  turnovers INTEGER,
  PF INTEGER,
  fgAttempted INTEGER,
  fgMade INTEGER,
  ftAttempted INTEGER,
  ftMade INTEGER,
  threeAttempted INTEGER,
  threeMade INTEGER,
  PostGP INTEGER,
  PostGS INTEGER,
  PostMinutes INTEGER,
  PostPoints INTEGER,
  PostoRebounds INTEGER,
  PostdRebounds INTEGER,
  PostRebounds INTEGER,
  PostAssists INTEGER,
  PostSteals INTEGER,
  PostBlocks INTEGER,
  PostTurnovers INTEGER,
  PostPF INTEGER,
  PostfgAttempted INTEGER,
  PostfgMade INTEGER,
  PostftAttempted INTEGER,
  PostftMade INTEGER,
  PostthreeAttempted INTEGER,
  PostthreeMade INTEGER,
  note TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (year) REFERENCES teams(year),
  FOREIGN KEY (tmID) REFERENCES teams(tmID)
);

CREATE TABLE series_post (
  id INTEGER,
  year INTEGER,
  round TEXT,
  series TEXT,
  tmIDWinner TEXT,
  lgIDWinner TEXT,
  tmIDLoser TEXT,
  lgIDLoser TEXT,
  W INTEGER,
  L INTEGER,
  PRIMARY KEY (id),
  FOREIGN KEY (year) REFERENCES teams(year),
  FOREIGN KEY (tmIDWinner) REFERENCES teams(tmID),
  FOREIGN KEY (tmIDLoser) REFERENCES teams(tmID)
);
