CREATE TABLE Demog (
  GEOID INTEGER,
  INHABITANTS_K REAL,
  INCOME_K REAL,
  A_VAR1 REAL,
  A_VAR2 REAL,
  A_VAR3 REAL,
  A_VAR4 REAL,
  A_VAR5 REAL,
  A_VAR6 REAL,
  A_VAR7 REAL,
  A_VAR8 REAL,
  A_VAR9 REAL,
  A_VAR10 REAL,
  A_VAR11 REAL,
  A_VAR12 REAL,
  A_VAR13 REAL,
  A_VAR14 REAL,
  A_VAR15 REAL,
  A_VAR16 REAL,
  A_VAR17 REAL,
  A_VAR18 REAL,
  PRIMARY KEY (GEOID)
);

CREATE TABLE mailings3 (
  REFID INTEGER,
  REF_DATE TEXT,
  RESPONSE TEXT,
  PRIMARY KEY (REFID)
);

CREATE TABLE Customers (
  ID INTEGER,
  SEX TEXT,
  MARITAL_STATUS TEXT,
  GEOID INTEGER,
  EDUCATIONNUM INTEGER,
  OCCUPATION TEXT,
  age INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE Mailings1_2 (
  REFID INTEGER,
  REF_DATE TEXT,
  RESPONSE TEXT,
  PRIMARY KEY (REFID)
);

CREATE TABLE Sales (
  EVENTID INTEGER,
  REFID INTEGER,
  EVENT_DATE TEXT,
  AMOUNT REAL,
  PRIMARY KEY (EVENTID)
);
