CREATE TABLE all_prevalences (
  ITEM TEXT,
  "POPULATION TYPE" TEXT,
  OCCURRENCES INTEGER,
  "POPULATION COUNT" INTEGER,
  "PREVALENCE RATE" REAL,
  "PREVALENCE PERCENTAGE" REAL,
  PRIMARY KEY (ITEM)
);

CREATE TABLE patients (
  patient TEXT,
  birthdate TEXT,
  deathdate TEXT,
  ssn TEXT,
  drivers TEXT,
  passport TEXT,
  prefix TEXT,
  first TEXT,
  last TEXT,
  suffix TEXT,
  maiden TEXT,
  marital TEXT,
  race TEXT,
  ethnicity TEXT,
  gender TEXT,
  birthplace TEXT,
  address TEXT,
  PRIMARY KEY (patient)
);

CREATE TABLE encounters (
  ID TEXT,
  DATE TEXT,
  PATIENT TEXT,
  CODE INTEGER,
  DESCRIPTION TEXT,
  REASONCODE INTEGER,
  REASONDESCRIPTION TEXT,
  PRIMARY KEY (ID),
  FOREIGN KEY (PATIENT) REFERENCES patients(patient)
);

CREATE TABLE allergies (
  START TEXT,
  STOP TEXT,
  PATIENT TEXT,
  ENCOUNTER TEXT,
  CODE INTEGER,
  DESCRIPTION TEXT,
  FOREIGN KEY (PATIENT) REFERENCES patients(patient),
  FOREIGN KEY (ENCOUNTER) REFERENCES encounters(ID)
);

CREATE TABLE careplans (
  ID TEXT,
  START TEXT,
  STOP TEXT,
  PATIENT TEXT,
  ENCOUNTER TEXT,
  CODE REAL,
  DESCRIPTION TEXT,
  REASONCODE INTEGER,
  REASONDESCRIPTION TEXT,
  FOREIGN KEY (PATIENT) REFERENCES patients(patient),
  FOREIGN KEY (ENCOUNTER) REFERENCES encounters(ID)
);

CREATE TABLE conditions (
  START TEXT,
  STOP TEXT,
  PATIENT TEXT,
  ENCOUNTER TEXT,
  CODE INTEGER,
  DESCRIPTION TEXT,
  FOREIGN KEY (PATIENT) REFERENCES patients(patient),
  FOREIGN KEY (ENCOUNTER) REFERENCES encounters(ID),
  FOREIGN KEY (DESCRIPTION) REFERENCES all_prevalences(ITEM)
);

CREATE TABLE immunizations (
  DATE TEXT,
  PATIENT TEXT,
  ENCOUNTER TEXT,
  CODE INTEGER,
  DESCRIPTION TEXT,
  FOREIGN KEY (PATIENT) REFERENCES patients(patient),
  FOREIGN KEY (ENCOUNTER) REFERENCES encounters(ID)
);

CREATE TABLE medications (
  START TEXT,
  STOP TEXT,
  PATIENT TEXT,
  ENCOUNTER TEXT,
  CODE INTEGER,
  DESCRIPTION TEXT,
  REASONCODE INTEGER,
  REASONDESCRIPTION TEXT,
  FOREIGN KEY (PATIENT) REFERENCES patients(patient),
  FOREIGN KEY (ENCOUNTER) REFERENCES encounters(ID)
);

CREATE TABLE observations (
  DATE TEXT,
  PATIENT TEXT,
  ENCOUNTER TEXT,
  CODE TEXT,
  DESCRIPTION TEXT,
  VALUE REAL,
  UNITS TEXT,
  FOREIGN KEY (PATIENT) REFERENCES patients(patient),
  FOREIGN KEY (ENCOUNTER) REFERENCES encounters(ID)
);

CREATE TABLE procedures (
  DATE TEXT,
  PATIENT TEXT,
  ENCOUNTER TEXT,
  CODE INTEGER,
  DESCRIPTION TEXT,
  REASONCODE INTEGER,
  REASONDESCRIPTION TEXT,
  FOREIGN KEY (PATIENT) REFERENCES patients(patient),
  FOREIGN KEY (ENCOUNTER) REFERENCES encounters(ID)
);

CREATE TABLE claims (
  ID TEXT,
  PATIENT TEXT,
  BILLABLEPERIOD TEXT,
  ORGANIZATION TEXT,
  ENCOUNTER TEXT,
  DIAGNOSIS TEXT,
  TOTAL INTEGER,
  PRIMARY KEY (ID)
);
